version: "3"

services:
  api:
    image: node:16
    volumes:
      - "./applications/api:/usr/src/api"
    working_dir: /usr/src/api
    user: node
    command: node main.js
    ports:
      - 3000:3000

  pwa:
    image: nginx:1.23.1-alpine
    volumes:
      - "./applications/pwa:/usr/share/nginx/html"
    working_dir: /usr/share/nginx/html
    ports:
      - 8080:80